steps:
  - name: "gcr.io/${PROJECT_ID}/terraform"
    args:
      [
        "-chdir=deploy/gcp/environments/${_ENV}",
        "init",
        "-backend-config=bucket=${_TFSTATE_BUCKET}",
      ]
  - name: "gcr.io/${PROJECT_ID}/terraform"
    args: ["-chdir=deploy/gcp/environments/${_ENV}", "apply", "-auto-approve"]
    env:
      - "TF_VAR_project_id=${PROJECT_ID}"
      - "TF_VAR_region=${_REGION}"
      - "TF_VAR_db_instance_tier=${_DB_INSTANCE_TIER}"
timeout: 1800s
